### ISSUE TITLE
Unmatched `}}` causes catastrophic rewindings

### ISSUE THREAD

**Issue by Evpok** [portstrom/parse_wiki_text#10]
An unmatched `}}` will cause as many rewinding warnings as there are `:` before, e.g.

```wikicode
:spam
::
::: Some line with spurious close }}
```

Gives

```
Output { nodes: [Text { end: 45, start: 0, value: ":spam\n::\n::: Some line with spurious close }}" }], warnings: [Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTagRewinding, start: 43 }, Warning { end: 45, message: UnexpectedEndTag, start: 43 }] }
```

Which can be problematic if it happens after heavy conversations, e.g. trying to parse <https://fr.wikipedia.org/wiki/Discussion:Extr%C3%AAme_gauche_en_France> ([permalink](https://gist.github.com/Evpok/2d0fc39a462a30ac8154b9991a3b6808)) result in the parser trying to allocate >15Gb RAM, at least I suspect that's the cause since removing either the `}}` (at `dans son esprit par Antonetti}}`) or all the colons allows the parser to proceed normally

**Comment by portstrom** [comment]
Unmatched `}}` shouldn't cause rewinding. `}}` should only cause rewinding of unterminated items that come after the matching `{{`. Will fix.

**Comment by portstrom** [comment]
Your test case parses with finite resources now.

**Comment by Evpok** [comment]
Thanks for being so reactive :-)

**Comment by Evpok** [comment]
Thanks for being so reactive :-)
