### ISSUE TITLE
Unreachable code reached when parsing documents containing too many exclamation marks.

### ISSUE THREAD

**Issue by annacrombie** [portstrom/parse_wiki_text#8]
# Encoutered
When parsing this xsd document: https://en.wikipedia.org/Special:Export/Nick_Cave

# Analysis
On line 120, there is a citation which appears to be parsed correctly, but when parsing the link title, it chokes.  The link title is: `"Nick Cave &amp; The Bad Seeds Dig!!! Lazarus Dig!!! (album review)"`

When the parser reaches the two consecutive exclamation marks near the end of Dig, it jumps to table::parse_heading_cell() which then calls get_table() which trys to match the last node in the stack with a table, but the node is a template so unreachable!() is called.

# Steps to Reproduce
1. Download https://en.wikipedia.org/Special:Export/Nick_Cave
2.  run `RUST_BACKTRACE=1 target/debug/examples/test file Nick_Cave.xsd`

**Comment by pbevin-tc** [comment]
SSCCE:

```
use parse_wiki_text::Configuration;
fn main() {
    println!("{:?}", Configuration::default().parse("!!"));
}
```

**Comment by pbevin** [comment]
SSCCE:

```
use parse_wiki_text::Configuration;
fn main() {
    println!("{:?}", Configuration::default().parse("!!"));
}
```

**Comment by portstrom** [comment]
Fixed. Thanks for reporting!

**Comment by Evpok** [comment]
Still seems active in the sandbox

**Comment by portstrom** [comment]
@Evpok I hadn't updated the sandbox. Now I have. Thanks for the reminder.
